package Corrida;

import java.util.Random;
import java.awt.Point;
import javax.swing.JOptionPane;

public class Interface extends javax.swing.JFrame {

            
    private int totalRespondidas;
    private int totalAcertos;
    public GeradorP perguntaSorteada;
    
    public Interface() {
        initComponents();
        setLocationRelativeTo(null);
        informativoLb.setVisible(false);
        getAlternativa.setVisible(false);
        btnResposta.setVisible(false);
        resultadoLb.setVisible(false);
        scoreLb.setVisible(false); 
    }
    
    public int getTotalRespondidas() {
        return totalRespondidas;
    }

    public void setTotalRespondidas(int totalRespondidas) {
        this.totalRespondidas = totalRespondidas;
    }

    public int getTotalAcertos() {
        return totalAcertos;
    }

    public void setTotalAcertos(int totalAcertos) {
        this.totalAcertos = totalAcertos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        informativoLb = new javax.swing.JLabel();
        getAlternativa = new javax.swing.JTextField();
        btnResposta = new javax.swing.JButton();
        perguntaLb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        resultadoLb = new javax.swing.JLabel();
        scoreLb = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Cavalo1 = new javax.swing.JLabel();
        Cavalo2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbchegada = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        perguntaLb1 = new javax.swing.JLabel();
        alternativaLb = new javax.swing.JLabel();
        btnStart = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Corrida De Cavalos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(342, 6, 234, 29);

        informativoLb.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        informativoLb.setForeground(new java.awt.Color(255, 0, 51));
        informativoLb.setText("Digite a alternativa escolhida: ");
        jPanel1.add(informativoLb);
        informativoLb.setBounds(6, 113, 185, 24);

        getAlternativa.setForeground(new java.awt.Color(255, 0, 51));
        getAlternativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAlternativaActionPerformed(evt);
            }
        });
        jPanel1.add(getAlternativa);
        getAlternativa.setBounds(197, 113, 139, 24);

        btnResposta.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnResposta.setForeground(new java.awt.Color(255, 0, 51));
        btnResposta.setText("Responder");
        btnResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespostaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResposta);
        btnResposta.setBounds(197, 65, 139, 30);

        perguntaLb.setBackground(new java.awt.Color(255, 0, 51));
        perguntaLb.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jPanel1.add(perguntaLb);
        perguntaLb.setBounds(430, 60, 520, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Pergunta:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 90, 80, 17);

        jSeparator1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 965, 10);

        resultadoLb.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        resultadoLb.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(resultadoLb);
        resultadoLb.setBounds(10, 70, 141, 39);

        scoreLb.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        scoreLb.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(scoreLb);
        scoreLb.setBounds(6, 143, 330, 84);

        jSeparator2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 237, 965, 10);

        Cavalo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Cavalo1.png"))); // NOI18N
        jPanel1.add(Cavalo1);
        Cavalo1.setBounds(6, 253, 236, 236);

        Cavalo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Cavalo2.png"))); // NOI18N
        jPanel1.add(Cavalo2);
        Cavalo2.setBounds(15, 470, 236, 236);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1647.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(703, 370, 256, 256);

        lbchegada.setBackground(new java.awt.Color(51, 51, 51));
        lbchegada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        lbchegada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("CHEGADA");

        javax.swing.GroupLayout lbchegadaLayout = new javax.swing.GroupLayout(lbchegada);
        lbchegada.setLayout(lbchegadaLayout);
        lbchegadaLayout.setHorizontalGroup(
            lbchegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
            .addGroup(lbchegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbchegadaLayout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
        );
        lbchegadaLayout.setVerticalGroup(
            lbchegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(lbchegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lbchegadaLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel9)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );

        jPanel1.add(lbchegada);
        lbchegada.setBounds(730, 240, 230, 390);

        perguntaLb1.setBackground(new java.awt.Color(255, 0, 51));
        perguntaLb1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jPanel1.add(perguntaLb1);
        perguntaLb1.setBounds(350, 150, 649, 56);

        alternativaLb.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        alternativaLb.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(alternativaLb);
        alternativaLb.setBounds(360, 140, 597, 84);

        btnStart.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 0, 0));
        btnStart.setText("Start Game");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(810, 0, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Jogador-1");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 250, 130, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Jogador-1");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 250, 150, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("MAQUINA");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 460, 132, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(979, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getAlternativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAlternativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getAlternativaActionPerformed

    private void btnRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespostaActionPerformed

        
        btnResposta.setVisible(false);

        String resposta1 = getAlternativa.getText();
        if(resposta1.equals(perguntaSorteada.getResposta())){
            getAlternativa.setText("");
            Point p = Cavalo1.getLocation();
            p.x = p.x + 190;
            Cavalo1.setLocation(p);
            resultadoLb.setText("Resposta certa !!!");
            setTotalRespondidas(getTotalRespondidas() + 1);
            setTotalAcertos(getTotalAcertos() + 1);

        }else{
            resultadoLb.setText("Resposta errada !!!");
            setTotalRespondidas(getTotalRespondidas() + 1);
            
            Point p = Cavalo2.getLocation();
            p.x = p.x + 190;
            Cavalo2.setLocation(p);

        }
        
        if(getTotalAcertos() > 3 ){
            JOptionPane.showMessageDialog(null,"Parabéns voce ganhou!!!!");
        }
       
    }//GEN-LAST:event_btnRespostaActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        Perguntas jogador1 = new Perguntas();

        Random aleatorio = new Random();

        btnStart.setText("Proxima pergunta");

        int sorteado = 1 + aleatorio.nextInt(20);

        perguntaSorteada = (GeradorP)jogador1.hashPerguntas.get(sorteado);

        perguntaLb.setText(perguntaSorteada.getEnumciado());
        alternativaLb.setText(perguntaSorteada.getAlternativa());

        informativoLb.setText("Digite a alternativa escolhida: ");
        btnResposta.setVisible(true);
        informativoLb.setVisible(true);
        getAlternativa.setVisible(true);
        resultadoLb.setVisible(true);
        scoreLb.setVisible(true);
        resultadoLb.setText(" ");
        scoreLb.setText(" ");
    }//GEN-LAST:event_btnStartActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cavalo1;
    private javax.swing.JLabel Cavalo2;
    private javax.swing.JLabel alternativaLb;
    private javax.swing.JButton btnResposta;
    private javax.swing.JToggleButton btnStart;
    private javax.swing.JTextField getAlternativa;
    private javax.swing.JLabel informativoLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel lbchegada;
    private javax.swing.JLabel perguntaLb;
    private javax.swing.JLabel perguntaLb1;
    private javax.swing.JLabel resultadoLb;
    private javax.swing.JLabel scoreLb;
    // End of variables declaration//GEN-END:variables
}
